version: '2.4'
services: 
    wsserver:
        restart: always
        ports: 
            - 8080:8080
        build: 
            context: ./backend
            dockerfile: Dockerfile   

    ngproxy:
        build:
            context: ./
            dockerfile: nginx/Dockerfile
        ports: 
            - 80:80
        restart: always
        depends_on:
            - wsserver
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro