version: '2.4'
services: 
    wsserver:
        restart: always
        ports: 
            - 8080:8080
        build: 
            context: ./backend
            dockerfile: Dockerfile   
    frontend:
        restart: always
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: frontend

    ngproxy:
        image: frontend
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports: 
            - 80:80
        restart: always
        depends_on:
            - wsserver
            - frontend
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro